name: echo

on:   
  push: 
  pull_request: 

jobs:
  A1:
    runs-on: ubuntu-24.04
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.1, 1.2]
        flag: [A, B, C, D, E, F, G, H, I, J]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: A1-Build
      uses: actions/checkout@v1
    - name: Main
      run: sleep 2
  OKE-1:
    needs: [A1]
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - name: Check Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: exit 1
      - name: Success
        if: ${{ success() }}
        run: echo "selesai"
  D1:
    needs: [OKE-1]
    runs-on: ubuntu-24.04
    strategy:
      max-parallel: 225
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9]
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y]
    env:
        NUM_JOBS: 225
        JOB: ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: D1-Build
      run: sleep 1
  OKE-2:
    needs: [A1, OKE-1, D1]
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - name: Check Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: exit 1
      - name: Success
        if: ${{ success() }}
        run: echo "selesai"
